#!/usr/bin/python2
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import argparse
from datetime import datetime
sys.path.append('/usr/lib/config-sync')
from vcc_param import VccParam

def getArgParser():
	parser = argparse.ArgumentParser()
	subparsers = parser.add_subparsers()

	parserEdit = subparsers.add_parser('edit', help='Start edit')
	parserEdit.set_defaults(op="edit")

	return parser

###############################################################################

param = VccParam()
args = getArgParser().parse_args()
if args.op == "edit":
	userLockFile = os.path.join(self.param.dataDir, "userlock")
	try:
		with open(userLockFile, "w") as f:
			pass
	finally:
		os.unlink(userLockFile)
else:
	raise Exception("Invalid sub command")
